services:
  - type: web
    name: auditoria-hospitalar
    env: docker
    plan: free
    repo: https://github.com/lucianogt3/auditoria-hospitalar
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: gunicorn auditoria_app:app --timeout 120 # Adicionado --timeout 120
    envVars:
  - key: RENDER
    value: "1"
