services:
  - type: web
    name: auditoria-hospitalar
    env: docker
    plan: free
    branch: main
    repo: https://github.com/lucianogt3/auditoria-hospitalar
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
