services:
  - type: web
    name: auditoria-hospitalar
    env: docker
    plan: free
    repo: https://github.com/lucianogt3/auditoria-hospitalar
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
