services:
  - type: web
    name: auditoria-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: gunicorn auditoria_app.app:app
