"""Add email confirmation fields to User

Revision ID: 00fcb6048c5d
Revises: 59e8acbd4f32
Create Date: 2025-05-17 17:30:19.395224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fcb6048c5d'
down_revision = '59e8acbd4f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('data_internacao',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_alta',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_auditoria',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fatura_de',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fatura_ate',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('confirmation_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_token', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('fatura_ate',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('fatura_de',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_auditoria',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_alta',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_internacao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('auditor')
    # ### end Alembic commands ###
