"""ajuste tipos de datas e horas

Revision ID: 1b5774662156
Revises: 5aa818538df0
Create Date: 2025-05-16 19:47:30.106818
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5774662156'
down_revision = '5aa818538df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestador', schema=None) as batch_op:
        # Altera o tipo do campo 'nome'
        batch_op.alter_column('nome',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=150),
            existing_nullable=False
        )

        # Cria a constraint única corretamente com nome
        batch_op.create_unique_constraint("uq_prestador_codigo", ['codigo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestador', schema=None) as batch_op:
        # Remove a constraint única
        batch_op.drop_constraint("uq_prestador_codigo", type_='unique')

        # Reverte o tipo do campo 'nome'
        batch_op.alter_column('nome',
            existing_type=sa.String(length=150),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False
        )
    # ### end Alembic commands ###
