"""criação inicial com campos de email

Revision ID: 2953ad2a241e
Revises: 
Create Date: 2025-05-18 21:56:20.019527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2953ad2a241e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_beneficiario', sa.String(length=255), nullable=False),
    sa.Column('cod_beneficiario', sa.String(length=50), nullable=True),
    sa.Column('cod_prestador', sa.String(length=50), nullable=True),
    sa.Column('nome_prestador', sa.String(length=255), nullable=True),
    sa.Column('guia_principal', sa.String(length=100), nullable=True),
    sa.Column('data_internacao', sa.DateTime(), nullable=True),
    sa.Column('hora_internacao', sa.String(length=10), nullable=True),
    sa.Column('data_alta', sa.DateTime(), nullable=True),
    sa.Column('hora_alta', sa.String(length=10), nullable=True),
    sa.Column('data_auditoria', sa.DateTime(), nullable=True),
    sa.Column('tipo_internacao', sa.String(length=50), nullable=True),
    sa.Column('caracter_internacao', sa.String(length=50), nullable=True),
    sa.Column('parcial', sa.String(length=50), nullable=True),
    sa.Column('cod_procedimento', sa.String(length=50), nullable=True),
    sa.Column('descricao_procedimento', sa.String(length=255), nullable=True),
    sa.Column('cid_codigo', sa.String(length=10), nullable=True),
    sa.Column('cid_descricao', sa.String(length=255), nullable=True),
    sa.Column('fatura_de', sa.DateTime(), nullable=True),
    sa.Column('fatura_ate', sa.DateTime(), nullable=True),
    sa.Column('grupo_1', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_1', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_1', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_1', sa.Float(), nullable=True),
    sa.Column('glosa_medico_1', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_1', sa.Float(), nullable=True),
    sa.Column('valor_liberado_1', sa.Float(), nullable=True),
    sa.Column('grupo_2', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_2', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_2', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_2', sa.Float(), nullable=True),
    sa.Column('glosa_medico_2', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_2', sa.Float(), nullable=True),
    sa.Column('valor_liberado_2', sa.Float(), nullable=True),
    sa.Column('grupo_3', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_3', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_3', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_3', sa.Float(), nullable=True),
    sa.Column('glosa_medico_3', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_3', sa.Float(), nullable=True),
    sa.Column('valor_liberado_3', sa.Float(), nullable=True),
    sa.Column('grupo_4', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_4', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_4', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_4', sa.Float(), nullable=True),
    sa.Column('glosa_medico_4', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_4', sa.Float(), nullable=True),
    sa.Column('valor_liberado_4', sa.Float(), nullable=True),
    sa.Column('grupo_5', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_5', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_5', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_5', sa.Float(), nullable=True),
    sa.Column('glosa_medico_5', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_5', sa.Float(), nullable=True),
    sa.Column('valor_liberado_5', sa.Float(), nullable=True),
    sa.Column('grupo_6', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_6', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_6', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_6', sa.Float(), nullable=True),
    sa.Column('glosa_medico_6', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_6', sa.Float(), nullable=True),
    sa.Column('valor_liberado_6', sa.Float(), nullable=True),
    sa.Column('grupo_7', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_7', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_7', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_7', sa.Float(), nullable=True),
    sa.Column('glosa_medico_7', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_7', sa.Float(), nullable=True),
    sa.Column('valor_liberado_7', sa.Float(), nullable=True),
    sa.Column('grupo_8', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_8', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_8', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_8', sa.Float(), nullable=True),
    sa.Column('glosa_medico_8', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_8', sa.Float(), nullable=True),
    sa.Column('valor_liberado_8', sa.Float(), nullable=True),
    sa.Column('grupo_9', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_9', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_9', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_9', sa.Float(), nullable=True),
    sa.Column('glosa_medico_9', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_9', sa.Float(), nullable=True),
    sa.Column('valor_liberado_9', sa.Float(), nullable=True),
    sa.Column('grupo_10', sa.String(length=100), nullable=True),
    sa.Column('qtd_apresentada_10', sa.Integer(), nullable=True),
    sa.Column('qtd_autorizada_10', sa.Integer(), nullable=True),
    sa.Column('valor_apresentado_10', sa.Float(), nullable=True),
    sa.Column('glosa_medico_10', sa.Float(), nullable=True),
    sa.Column('glosa_enfermagem_10', sa.Float(), nullable=True),
    sa.Column('valor_liberado_10', sa.Float(), nullable=True),
    sa.Column('linhaextra_grupo_1', sa.String(length=100), nullable=True),
    sa.Column('linhaextra_qtd_apresentada_1', sa.Integer(), nullable=True),
    sa.Column('linhaextra_qtd_autorizada_1', sa.Integer(), nullable=True),
    sa.Column('linhaextra_valor_apresentado_1', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_medico_1', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_enfermagem_1', sa.Float(), nullable=True),
    sa.Column('linhaextra_valor_liberado_1', sa.Float(), nullable=True),
    sa.Column('linhaextra_grupo_2', sa.String(length=100), nullable=True),
    sa.Column('linhaextra_qtd_apresentada_2', sa.Integer(), nullable=True),
    sa.Column('linhaextra_qtd_autorizada_2', sa.Integer(), nullable=True),
    sa.Column('linhaextra_valor_apresentado_2', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_medico_2', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_enfermagem_2', sa.Float(), nullable=True),
    sa.Column('linhaextra_valor_liberado_2', sa.Float(), nullable=True),
    sa.Column('linhaextra_grupo_3', sa.String(length=100), nullable=True),
    sa.Column('linhaextra_qtd_apresentada_3', sa.Integer(), nullable=True),
    sa.Column('linhaextra_qtd_autorizada_3', sa.Integer(), nullable=True),
    sa.Column('linhaextra_valor_apresentado_3', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_medico_3', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_enfermagem_3', sa.Float(), nullable=True),
    sa.Column('linhaextra_valor_liberado_3', sa.Float(), nullable=True),
    sa.Column('linhaextra_grupo_4', sa.String(length=100), nullable=True),
    sa.Column('linhaextra_qtd_apresentada_4', sa.Integer(), nullable=True),
    sa.Column('linhaextra_qtd_autorizada_4', sa.Integer(), nullable=True),
    sa.Column('linhaextra_valor_apresentado_4', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_medico_4', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_enfermagem_4', sa.Float(), nullable=True),
    sa.Column('linhaextra_valor_liberado_4', sa.Float(), nullable=True),
    sa.Column('linhaextra_grupo_5', sa.String(length=100), nullable=True),
    sa.Column('linhaextra_qtd_apresentada_5', sa.Integer(), nullable=True),
    sa.Column('linhaextra_qtd_autorizada_5', sa.Integer(), nullable=True),
    sa.Column('linhaextra_valor_apresentado_5', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_medico_5', sa.Float(), nullable=True),
    sa.Column('linhaextra_glosa_enfermagem_5', sa.Float(), nullable=True),
    sa.Column('linhaextra_valor_liberado_5', sa.Float(), nullable=True),
    sa.Column('total_apresentado', sa.Float(), nullable=True),
    sa.Column('total_glosa_medico', sa.Float(), nullable=True),
    sa.Column('total_glosa_enfermagem', sa.Float(), nullable=True),
    sa.Column('total_liberado', sa.Float(), nullable=True),
    sa.Column('auditor', sa.String(length=100), nullable=True),
    sa.Column('acomodacao', sa.String(length=50), nullable=True),
    sa.Column('motivo_glosa', sa.Text(), nullable=True),
    sa.Column('salvo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('prestador')
    op.drop_table('cid')
    op.drop_table('auditoria')
    op.drop_table('auditor')
    # ### end Alembic commands ###
