"""Criação inicial das tabelas

Revision ID: 4edaee207991
Revises: 
Create Date: 2025-05-03 05:18:00.600956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edaee207991'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_beneficiario', sa.String(length=255), nullable=False),
    sa.Column('cod_beneficiario', sa.String(length=50), nullable=True),
    sa.Column('cod_prestador', sa.String(length=50), nullable=True),
    sa.Column('nome_prestador', sa.String(length=255), nullable=True),
    sa.Column('guia_principal', sa.String(length=100), nullable=True),
    sa.Column('data_internacao', sa.String(length=20), nullable=True),
    sa.Column('hora_internacao', sa.String(length=10), nullable=True),
    sa.Column('data_alta', sa.String(length=20), nullable=True),
    sa.Column('hora_alta', sa.String(length=10), nullable=True),
    sa.Column('data_auditoria', sa.String(length=20), nullable=True),
    sa.Column('tipo_internacao', sa.String(length=50), nullable=True),
    sa.Column('caracter_internacao', sa.String(length=50), nullable=True),
    sa.Column('parcial', sa.String(length=50), nullable=True),
    sa.Column('cod_procedimento', sa.String(length=50), nullable=True),
    sa.Column('descricao_procedimento', sa.String(length=255), nullable=True),
    sa.Column('cid_codigo', sa.String(length=10), nullable=True),
    sa.Column('cid_descricao', sa.String(length=255), nullable=True),
    sa.Column('fatura_de', sa.String(length=20), nullable=True),
    sa.Column('fatura_ate', sa.String(length=20), nullable=True),
    sa.Column('total_apresentado', sa.Float(), nullable=True),
    sa.Column('total_glosa_medico', sa.Float(), nullable=True),
    sa.Column('total_glosa_enfermagem', sa.Float(), nullable=True),
    sa.Column('total_liberado', sa.Float(), nullable=True),
    sa.Column('salvo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('prestador')
    op.drop_table('cid')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
