"""Adiciona campo ativo em Prestador

Revision ID: 5aa818538df0
Revises: a82e6862c3d6
Create Date: 2025-05-10 08:10:48.323290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa818538df0'
down_revision = 'a82e6862c3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestador', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
