"""Adiciona auditor, acomodacao e motivo_glosa

Revision ID: a82e6862c3d6
Revises: 14e2db393a4d
Create Date: 2025-05-10 07:28:32.539793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82e6862c3d6'
down_revision = '14e2db393a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auditor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('acomodacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('motivo_glosa', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('motivo_glosa')
        batch_op.drop_column('acomodacao')
        batch_op.drop_column('auditor')

    # ### end Alembic commands ###
