"""Corrige campos no modelo User

Revision ID: d860c4a881a8
Revises: 00fcb6048c5d
Create Date: 2025-05-17 17:33:09.316161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd860c4a881a8'
down_revision = '00fcb6048c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmation_token')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
